name: flutter_beep
description: A very lite module to play system sounds and beep for flutter apps (no sound files)
version: 1.2.0
homepage: https://github.com/trietho/flutter_beep.git

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.gonoter.flutter_beep
        pluginClass: FlutterBeepPlugin
      ios:
        pluginClass: FlutterBeepPlugin
